/*
	AUTHOR: SARMED RIZVI
   SUMMARY: THE COMMON VARIABLES WILL BE STORED HERE. THAT ARE ACCESSIBLE IN WHOLE APP.
*/

// EXPORT GLOBAL VARIABLES TO THE APPLICATION.
export const globals = {
  siteVariables: [], // LIST OF SITE VARIABLES FORM SITEVARIABLE TABLE.
  messages: [], // LIST OF SITE MESSAGES FORM MESSAGE TABLE.
  languages: [], // LIST OF AVAILABLE LANGUAGES.
  days: [], // LIST OF AVAILABLE LANGUAGES.
  socket: null, // SOCKET.IO OBJECT TO BE USED IN THE APP.
  language_id: null, // USER SELECTED LANGUAGE FOR THE APP.
  appVersion: "1.0.0", // CURRENT APP VERSION.
  lastUpdated: "Dec 17", // WHEN WAS THIS APP UPDATED.
};

// THIS FUNCTION WILL RECEIVE VARIABLES FROM SITE VARIABLE OR FROM LOCAL STORAGE. IT WILL SET THE GLOBAL
// VARIABLES SO THEY CAN BE USED IN APP.
export const setGlobalVariables = (data) => {
  globals.siteVariables = data.siteVariables; // STORE THE SITE VARIABLES INTO GLOBAL VARIABLE.
  globals.messages = data.messages; // STORE THE SITE MESSAGES INTO GLOBAL VARIABLE.
  globals.languages = data.languages; // STORE THE LANGUAGES INFORMATION INTO GLOBAL VARIABLE.
  globals.days = data.days; // STORE THE AVAILABLE DAYS INTO GLOBAL VARIABLE.
};
